Repository NiceAesth/aiosu, pull requests merged in 2022-12, with the labels that each got.

#28 Events
  Makefile
  aiosu/classes/__init__.py
  aiosu/classes/events.py
  aiosu/v1/client.py
  aiosu/v2/client.py
  aiosu/v2/clientstorage.py
  docs/source/classes/index.rst
  tests/test_v2/test_client.py
  tests/test_v2/test_clientstorage.py
  tests/test_v2/test_events.py
Labels: size/L

#29 Add TYPE_CHECKING to typing imports
  .github/CONTRIBUTING.rst
  aiosu/classes/beatmap.py
  aiosu/classes/events.py
  aiosu/classes/legacy/match.py
  aiosu/classes/models.py
  aiosu/classes/mods.py
  aiosu/classes/score.py
  aiosu/classes/token.py
  aiosu/classes/user.py
  aiosu/helpers.py
  aiosu/utils/performance.py
  aiosu/v1/client.py
  aiosu/v2/client.py
  aiosu/v2/clientstorage.py
Labels: size/L

#30 Add request_beatmap() for API v1 scores, fix null values in API v1, fix default limits
  aiosu/classes/beatmap.py
  aiosu/classes/score.py
  aiosu/classes/user.py
  aiosu/v1/client.py
  aiosu/v2/client.py
  tests/test_v1/test_client.py
Labels: size/L

#33 Implement new event system
  .pre-commit-config.yaml
  Makefile
  aiosu/classes/events.py
  aiosu/v2/client.py
  aiosu/v2/clientstorage.py
  pyproject.toml
  tests/test_utils/test_accuracy.py
  tests/test_utils/test_pp.py
Labels: size/L

#34 Add auth utils
  aiosu/utils/auth.py
  docs/source/utils/index.rst
Labels: size/M

#36 Auth util
  aiosu/utils/auth.py
  pyproject.toml
Labels: size/XS

#37 Add scope checking
  aiosu/classes/__init__.py
  aiosu/classes/scopes.py
  aiosu/classes/token.py
  aiosu/v2/client.py
  aiosu/v2/clientstorage.py
  tests/test_misc/test_token.py
  tests/test_v2/test_client.py
  tests/test_v2/test_clientstorage.py
  tests/test_v2/test_events.py
Labels: size/L

#38 Score replay download
  aiosu/v2/client.py
  tests/data/replay_fruits.osr
  tests/data/replay_mania.osr
  tests/data/replay_osu.osr
  tests/data/replay_taiko.osr
  tests/test_v2/test_client.py
Labels: size/M

#40 Get score
  aiosu/classes/user.py
  aiosu/v2/client.py
  tests/data/v2/single_score_fruits.json
  tests/data/v2/single_score_mania.json
  tests/data/v2/single_score_osu.json
  tests/data/v2/single_score_taiko.json
  tests/test_v2/test_client.py
Labels: size/M

#41 Get seasonal bg
  aiosu/classes/__init__.py
  aiosu/classes/backgrounds.py
  aiosu/v2/client.py
  docs/source/classes/index.rst
  tests/data/v2/seasonal_backgrounds.json
  tests/test_utils/test_accuracy.py
  tests/test_utils/test_pp.py
  tests/test_v1/test_client.py
  tests/test_v2/test_client.py
  tests/test_v2/test_clientstorage.py
  tests/test_v2/test_events.py
Labels: size/M

#42 Get beatmapset
  aiosu/v2/client.py
  tests/data/v2/single_beatmapset_fruits.json
  tests/data/v2/single_beatmapset_mania.json
  tests/data/v2/single_beatmapset_osu.json
  tests/data/v2/single_beatmapset_taiko.json
  tests/test_v2/test_client.py
Labels: size/M

#43 Refactor requests
  aiosu/classes/score.py
  aiosu/v1/client.py
  aiosu/v2/client.py
  docs/source/clients/v1/index.rst
  docs/source/clients/v2/index.rst
  tests/classes/mock.py
  tests/test_v2/test_client.py
  tests/test_v2/test_events.py
Labels: size/L

#44 Lookup beatmapset
  aiosu/v2/client.py
  tests/test_v2/test_client.py
Labels: size/S

#45 Get beatmaps
  aiosu/v2/client.py
  tests/data/v2/multiple_beatmap.json
  tests/test_v2/test_client.py
Labels: size/M

#46 Search beatmapsets
  aiosu/v2/client.py
  tests/data/v2/multiple_beatmapset.json
  tests/test_v2/test_client.py
Labels: size/M

#47 Get users
  aiosu/v2/client.py
  tests/data/v2/multiple_user.json
  tests/test_v2/test_client.py
Labels: size/M

#48 Add revoke_token
  aiosu/v2/client.py
Labels: size/S

#52 Get changelog
  aiosu/events.py
  aiosu/helpers.py
  aiosu/models/changelog.py
  aiosu/models/legacy/match.py
  aiosu/models/mods.py
  aiosu/models/score.py
  aiosu/models/token.py
  aiosu/models/user.py
  aiosu/utils/accuracy.py
  aiosu/utils/performance.py
  aiosu/v1/client.py
  aiosu/v2/client.py
  aiosu/v2/clientstorage.py
  tests/data/v2/single_changelog.json
  tests/test_v2/test_client.py
Labels: size/L

#53 Spotlights
  aiosu/models/__init__.py
  aiosu/models/spotllight.py
  aiosu/v2/client.py
  docs/source/models/index.rst
  tests/data/v2/multiple_spotlight.json
  tests/test_v2/test_client.py
Labels: size/M

#54 Get news
  aiosu/models/__init__.py
  aiosu/models/news.py
  aiosu/v2/client.py
  tests/data/v2/single_news_post.json
  tests/test_v2/test_client.py
Labels: size/L

#55 Get wiki
  aiosu/models/__init__.py
  aiosu/models/wiki.py
  aiosu/v2/client.py
  tests/data/v2/single_wiki_page.json
  tests/test_v2/test_client.py
Labels: size/M

#56 Get user kudosu
  aiosu/models/__init__.py
  aiosu/models/kudosu.py
  aiosu/v2/client.py
  docs/source/models/index.rst
  tests/data/v2/kudosu_history.json
  tests/test_v2/test_client.py
Labels: size/M

#57 Search
  aiosu/models/__init__.py
  aiosu/models/search.py
  aiosu/v2/client.py
  docs/source/models/index.rst
  tests/data/v2/search.json
  tests/test_v2/test_client.py
Labels: size/M

#58 Add ranking model
  aiosu/models/__init__.py
  aiosu/models/rankings.py
  aiosu/models/spotlight.py
  docs/source/models/index.rst
Labels: size/M

#59 Add get user beatmap, get user most played
  aiosu/models/__init__.py
  aiosu/models/user.py
  aiosu/v2/client.py
  tests/data/v2/multiple_user_beatmapset.json
  tests/data/v2/multiple_user_playcount.json
  tests/test_v2/test_client.py
Labels: size/L

#60 Add get user recent activity
  aiosu/models/__init__.py
  aiosu/models/event.py
  aiosu/v2/client.py
  docs/source/models/index.rst
  tests/data/v2/multiple_event.json
  tests/test_v2/test_client.py
Labels: size/L

#63 Add get_own_friends
  aiosu/v2/client.py
  tests/data/v2/multiple_beatmapset_event.json
  tests/test_v2/test_client.py
Labels: size/S

#65 Handle downloading of osu! maps from original /osu/ endpoint
  aiosu/v1/client.py
  aiosu/v2/client.py
Labels: size/S

#66 Add tests, decode text/plain instead
  aiosu/v1/client.py
  aiosu/v2/client.py
  tests/data/beatmap.osu
  tests/test_v1/test_client.py
Labels: size/XL

#67 Downgrade sphinx
  pyproject.toml
Labels: size/XS
