Repository NiceAesth/aiosu, pull requests merged in 2023-07, with the labels that each got.

#150 chore: maintenance in preparation for v2
  .pre-commit-config.yaml
  Makefile
  aiosu/v1/client.py
  aiosu/v2/client.py
Labels: size/L

#151 [feat] aiosu v2.0.0
  README.rst
  aiosu/models/artist.py
  aiosu/models/base.py
  aiosu/models/beatmap.py
  aiosu/models/changelog.py
  aiosu/models/chat.py
  aiosu/models/comment.py
  aiosu/models/common.py
  aiosu/models/event.py
  aiosu/models/forum.py
  aiosu/models/kudosu.py
  aiosu/models/lazer.py
  aiosu/models/legacy/match.py
  aiosu/models/mods.py
  aiosu/models/multiplayer.py
  aiosu/models/news.py
  aiosu/models/oauthtoken.py
  aiosu/models/rankings.py
  aiosu/models/replay.py
  aiosu/models/score.py
  aiosu/models/search.py
  aiosu/models/spotlight.py
  aiosu/models/user.py
  aiosu/models/wiki.py
  aiosu/utils/auth.py
  aiosu/utils/replay.py
  aiosu/v1/client.py
  aiosu/v2/client.py
  docs/source/index.rst
  docs/source/quickstart.rst
  examples/models.py
  examples/v2/custom_repository.py
  pyproject.toml
  tests/data/v2/multiple_beatmap.json
  tests/data/v2/multiple_beatmapset.json
  tests/data/v2/multiple_beatmapset_discussion.json
  tests/data/v2/multiple_user_beatmapset.json
  tests/data/v2/rankings_fruits_charts.json
  tests/data/v2/rankings_mania_charts.json
  tests/data/v2/rankings_osu_charts.json
  tests/data/v2/rankings_taiko_charts.json
  tests/data/v2/single_beatmap_fruits.json
  tests/data/v2/single_beatmap_mania.json
  tests/data/v2/single_beatmap_osu.json
  tests/data/v2/single_beatmap_taiko.json
  tests/data/v2/single_beatmapset_fruits.json
  tests/data/v2/single_beatmapset_mania.json
  tests/data/v2/single_beatmapset_osu.json
  tests/data/v2/single_beatmapset_taiko.json
  tests/test_misc/test_models.py
  tests/test_misc/test_token.py
  tests/test_utils/test_accuracy.py
  tests/test_utils/test_pp.py
  tests/test_utils/test_replay.py
  tests/test_v2/test_events.py
Labels: size/XXL

#152 feat: change docs to furo theme
  docs/source/conf.py
  docs/source/index.rst
  pyproject.toml
Labels: size/S

#153 feat: move file related models to separate directory
  aiosu/models/__init__.py
  aiosu/models/files/__init__.py
  aiosu/models/files/replay.py
  aiosu/utils/replay.py
  docs/source/models/index.rst
  examples/utils.py
  tests/test_utils/test_replay.py
Labels: size/M
