Repository NiceAesth/aiosu, pull requests merged in 2023-08, with the labels that each got.

#160 fix: remove exceptions from `computed_field()`
  aiosu/models/beatmap.py
  aiosu/models/common.py
  aiosu/models/lazer.py
  aiosu/models/oauthtoken.py
  aiosu/models/score.py
  aiosu/models/user.py
Labels: size/XXL

#164 fix: typos in models
  aiosu/models/common.py
  aiosu/models/event.py
Labels: size/XS

#166 feat: add more literal types
  aiosu/models/artist.py
  aiosu/models/changelog.py
  aiosu/models/chat.py
  aiosu/models/comment.py
  aiosu/models/common.py
  aiosu/models/lazer.py
  aiosu/models/multiplayer.py
  aiosu/models/news.py
  aiosu/models/spotlight.py
  aiosu/v2/client.py
  docs/source/models/index.rst
Labels: size/L

#168 fix: only cast to datetime if str
  aiosu/models/common.py
Labels: size/XS

#169 feat: add events endpoint
  aiosu/models/event.py
  aiosu/v2/client.py
  tests/data/v2/multiple_cursor_event.json
  tests/test_v2/test_client.py
Labels: size/XL

#170 fix: change type of `UserLevel.progress` to int
  aiosu/models/user.py
Labels: size/XS

#172 fix: possible division by 0 in `average_gain`
  aiosu/models/user.py
  aiosu/utils/performance.py
Labels: size/XS
